some clean up in readme, citation, contribution and tutorial edits
mdenolle/NoisePy pull request #105
Opened 2023-05-07 18:26 UTC by mdenolle

reformatted/modified a bit the readme, citation, and contribution.

Corrected a typo in noise_module. 

Edited the tutorial to run on colab, but specifically to add parameter configurations and such. step2 (stacking) still not edited for it to work.

Added a few print statements because I am surprised it takes so long to remove the instrumental response. Ideally, we would also just profile a bit the steps between download, basic pre-process, FFT, cross correlations.

2023-05-07 18:28 UTC, mdenolle commented
sorry for the conflicts, i don't know how to fix them

2023-05-08 15:51 UTC, carlosgjs requested changes

2023-05-08 15:51 UTC, carlosgjs commented on README.md
> +## Use this reference when publishing on your work with noisepy
Should this go into the `citation.cff` file instead?

2023-05-08 15:51 UTC, carlosgjs commented on README.md
> + *   #  TODO: change "no" for "None", and add "one_bit" as an option
This is markdown, so lines that start with `#` become headers. You can preview this in VS Code ( right-click on the file and Open Preview. I also suggest removing all `# TODO` comments from here.

<img width="530" alt="image" src="https://user-images.githubusercontent.com/10456546/236870148-3ceb7695-cd44-4b37-b448-e7efbcd4e340.png">

2023-05-08 19:29 UTC, carlosgjs approved these changes

2023-05-08 21:13 UTC, merged