Zarr file saving implementation
mdenolle/NoisePy pull request #115
Opened 2023-05-11 20:13 UTC by nrich20

Created a zarrstore.py file that is similar to the asfstore.py file except it saves the data in the zarr file format.

2023-05-12 16:27 UTC, carlosgjs requested changes
Great progress! Some inline comments.

2023-05-12 16:27 UTC, carlosgjs commented on README.md
> +conda create -n noisepy python=3.8 pip
bad merge?

2023-05-12 16:27 UTC, carlosgjs commented on pyproject.toml
> +    { email = "mdenolle@uw.edu", name = "Marine Denolle" },
```suggestion
```

2023-05-12 16:27 UTC, carlosgjs commented on pyproject.toml
> +    "DateTimeRange==2.0.0",
```suggestion
```

2023-05-12 16:27 UTC, carlosgjs commented on src/noisepy/seis/zarrstore.py
> +import datetime
@nrich20 , can you move this to a separate PR? All of the above is about the txt->csv/json conversion

2023-05-25 21:28 UTC, nrich20 commented
Due to many merge errors and other conflicts, this branch has become inoperable. Closing this pull request and will reopen this issue on a clean branch.

2023-05-25 21:28 UTC, closed without merging