Moving Tutorial from README to Jupiter notebook.
mdenolle/NoisePy pull request #81
Opened 2023-04-10 20:51 UTC by nrich20

I have removed the tutorial from the README file and have put a small note in its place with a link to the Jupyter Notebook tutorial. The link will not currently work since its set to access the master branch, but the Jupyter tutorial doesn't exist in that branch until this merge.

2023-04-10 21:38 UTC, carlosgjs requested changes

2023-04-10 21:38 UTC, carlosgjs commented on Jupyter_notebook/tutorial.ipynb
> +        "This tutorial will walk you through the basic steps of using NoisePy to compute ambient noise cross correlation functions.\n",
Please take a look at the latest version of the [colab notebook](https://colab.research.google.com/drive/1ir-p05dW34cj4biEZYqa7QXgXpjqv3fW#scrollTo=rR860zaZPZGH). The installation is now done through:
```
!pip install noisepy-seis
```
So there's no need to clone the repo, install requirements or cd to `src`.

2023-04-10 21:38 UTC, carlosgjs commented on Jupyter_notebook/tutorial.ipynb
> +            "image/png": "iVBORw0KGgoAAAANSUhEUgAAA3kAAAJOCAYAAAAK+M50AAAAOXRFWHRTb2Z0d2FyZQBNYXRwbG90bGliIHZlcnNpb24zLjcuMSwgaHR0cHM6Ly9tYXRwbG90bGliLm9yZy/bCgiHAAAACXBIWXMAAA9hAAAPYQGoP6dpAAEAAElEQ
The last time I was playing with it, this step wasn't working. Can you do a little digging to see what may be going on?

2023-04-13 21:57 UTC, carlosgjs requested changes
Getting there! Looks like there are some artifacts from merge conflicts.

2023-04-13 21:57 UTC, carlosgjs commented on CONTRIBUTING.md
> +$ pip install -e ".[dev]"
```suggestion
```

2023-04-13 21:57 UTC, carlosgjs commented on CONTRIBUTING.md
> +$ pre-commit install
```suggestion
```

2023-04-13 21:57 UTC, carlosgjs commented on Jupyter_notebook/tutorial.ipynb
> +            "Collecting noisepy-seis\n",
Can you clear all the outputs before committing the notebook?

2023-04-13 21:57 UTC, carlosgjs commented on README.md
> +<img src="https://raw.githubusercontent.com/mdenolle/NoisePy/master/docs/figures/logo.png" width="800" height="400">
duplicated?
```suggestion
```

2023-04-13 21:57 UTC, carlosgjs commented on README.md
> +* adding options for several stacking methods such as nth-root, robust-stacking, auto-covariance and selective. A script is added to the folder of application_modules to cross-compare the effects of
```suggestion
```

2023-04-13 21:57 UTC, carlosgjs commented on README.md
> +$ conda create -n noisepy python=3.8 pip
Also several duplicated lines in this section, probably from a bad merge

2023-04-13 21:57 UTC, carlosgjs commented on test/test_routines/test_stretching.py
> +import time
this file was moved to `unittests/.`, can you remove it from here?

2023-04-13 23:35 UTC, niyiyu approved these changes
Thanks Nick!

2023-04-17 21:06 UTC, carlosgjs approved these changes

2023-04-18 19:33 UTC, merged